### PR TITLE
modeling_albert.py

### PR DESCRIPTION
**Pull request by lsy641**
Today I tried to accomplish part of modeling_albert.py. Since AlbertEmbeddings seems equivalent with BertEmbeddings and AlbertAttention equivalent with BertAttention plus BertSelfOutput, I just modified a little in function from_torch() to adjust parameters to AlbertConfig and just let the classes inherit cxx.BertEmbeddings and cxx.BertAttention.
I think it is ok , but when I do unitest, running time is  very long.  Do you know why?

image

### CODE REVIEW

**Comment by feifeibear** [comment]
You should reuse BertAttention and BertEmbedding to construct an Albert. Albert is some kind of BERT and uses BertXXX as its building block is totally reasonable.
It is a bad idea to write an attention layer with the same function but a different name. It will introduce some duplicated code.

**Comment by feifeibear** [comment]
Actually, we have all the required building blocks for Albert.
Attn + gemm + AddBiasAdd + gem + AddBiasLayerNorm
You can create a `modeling_albert.py` and assembly these kernels into an Albert class.

**Comment by lsy641** [comment]
> You should reuse BertAttention and BertEmbedding to construct an Albert. Albert is some kind of BERT and uses BertXXX as its building block is totally reasonable.
> It is a bad idea to write an attention layer with the same function but a different name. It will introduce some duplicated code.

略微不懂，Albert和Bert的Embeddings实现完全一样，如果我用你们提供的模块再组装一遍也是重复代码吧？
以下是huggingface提供的两份模型实现。
image
image

**Comment by feifeibear** [comment]
1. Did you check the parameter of Albert. It may be different from BERT.
2. You run 100 times embedding untest
3. you can go to the build directory, and use `ctest -V -R albert` to see detail benchmarking results.

**Comment by feifeibear** [comment]
https://github.com/Tencent/TurboTransformers/pull/57
参考这个PR来贡献代码吧

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/TurboTransformers?pullRequest=48) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/TurboTransformers?pullRequest=48) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: lsy641<br/>:x: feifeibear<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/TurboTransformers?pullRequest=48) it.</sub>

**Comment by lsy641** [comment]
> [CLA assistant check](https://cla.opensource.tencent.com/Tencent/TurboTransformers?pullRequest=48)
> Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/TurboTransformers?pullRequest=48) before we can accept your contribution.
> **0** out of **2** committers have signed the CLA.
> 
> ❌ lsy641
> ❌ feifeibear
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/TurboTransformers?pullRequest=48) it.

我打不开这个网址 @tencent-adm @feifeibear

**Comment by lsy641** [comment]
打开了，这个关闭，我重新开一个draft

**Pull request closed without merging**
