### PR TITLE
feature:add python encoder wrapper

### PR DESCRIPTION
**Pull request by vuuihc**
1. extract MultiHeadedAttention and PositionwiseFeedForward to a single file
2. add TransformerEncoder

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/TurboTransformers?pullRequest=235) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/TurboTransformers?pullRequest=235) before we can accept your contribution.<br/><hr/>**jacksonzhu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/TurboTransformers?pullRequest=235) it.</sub>

**Review by feifeibear — COMMENTED** [review]
LGTM
能否加一个单测？这样每次改动可以判断encoder是否正常work。

**Comment by vuuihc** [comment]
> LGTM
> 能否加一个单测？这样每次改动可以判断encoder是否正常work。

单测已加

**Review by feifeibear — APPROVED** [review]
LGTM

**Pull request merged**
