### PR TITLE
Develop: Add QBertLayer

### PR DESCRIPTION
**Pull request by flans39**
```
seq length = 10
torch fp32 layer QPS = 286.87848355287684
turbo fp32+int8 layer QPS = 593.249552690575
torch int8 layer QPS = 966.0800125300294
seq length = 20
torch fp32 layer QPS = 199.05944820771683
turbo fp32+int8 layer QPS = 386.56004010937914
torch int8 layer QPS = 630.6636073027778
seq length = 40
torch fp32 layer QPS = 117.05113904494421
turbo fp32+int8 layer QPS = 219.72384066618542
torch int8 layer QPS = 322.2409256264381
seq length = 60
torch fp32 layer QPS = 89.74462721341733
turbo fp32+int8 layer QPS = 156.93398511966566
torch int8 layer QPS = 255.3087465821299
seq length = 80
torch fp32 layer QPS = 70.42333546681209
turbo fp32+int8 layer QPS = 118.96652415733189
torch int8 layer QPS = 200.277426683672
seq length = 100
torch fp32 layer QPS = 57.26683852754883
turbo fp32+int8 layer QPS = 93.85800496601307
torch int8 layer QPS = 165.84136845193518
seq length = 200
torch fp32 layer QPS = 29.851458832704665
turbo fp32+int8 layer QPS = 46.9782432799324
torch int8 layer QPS = 82.75075617542441
seq length = 300
torch fp32 layer QPS = 19.09736564697586
turbo fp32+int8 layer QPS = 28.965161662435577
torch int8 layer QPS = 50.98322173103814
max error against torch fp32 =  tensor(0.1685)
max error against torch int8 =  tensor(0.1014)
```

### CODE REVIEW

**Comment by feifeibear** [comment]
> max error against torch fp32 =  tensor(0.1685)
> max error against torch int8 =  tensor(0.1014)

Speed looks fine, but the error is quiet larger. Anyway, we can test the accuracy in a real classification task after BertModel ready.

**Comment by feifeibear** [comment]
As we still not quantize the QKV MatMul, the performance gap between ours and torch dynamic quantization may be further decreased.

**Comment by flans39** [comment]
> As we still not quantize the QKV MatMul, the performance gap between ours and torch dynamic quantization may be further decreased.
Well, the max error between torch int8 and torch fp32 = tensor(0.1742). If we quantize the QKV MatMul, turbo's error against torch int8 should approach zero, but the error against torch fp32 is still large.

**Comment by feifeibear** [comment]
> > As we still not quantize the QKV MatMul, the performance gap between ours and torch dynamic quantization may be further decreased.
> 
> Well, the max error between torch int8 and torch fp32 = tensor(0.1742). If we quantize the QKV MatMul, turbo's error against torch int8 should approach zero, but the error against torch fp32 is still large.

OK, left QKV along right now. I may refactor the attention layer these days and split QKV Matmul out. 
Let's finish QBertModel first and run it through in a real task.
https://github.com/Tencent/TurboTransformers/blob/master/example/python/bert_for_sequence_classification_example.py

**Pull request merged**
